# This workflow is separated from pytest-unit-tests.yml
# to bypass a security restriction in GitHub Actions
# which resulted in failing workflows at PR's
# See & read: https://github.com/dorny/test-reporter#README

# CI Pull Request on pr -> Test Report CI Pull Request
# CI Push on push       -> Test Report

# This workflow is triggered after worklflow "CI Pull Request"
name: "Test Report"
on:
  workflow_run:
    workflows: ['CI Pull Request', 'CI Push']
    #branches: [main, development, feature/*, hotfix/*]
    #branches-ignore:
    types:
      - completed

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        artifact: test-results
        name: Workflow Report
        path: '*.xml'
        reporter: jest-junit
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Report
        path: tests/junit/test-results*.xml
        reporter: java-junit
